src/main/java/ru/javabegin/training/web/entity/Genre.java
package ru.javabegin.training.web.entity;
// Generated Jul 5, 2013 2:59:07 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Genre generated by hbm2java
 */
public class Genre implements java.io.Serializable {

    private Long id;
    private String name;
    private Set books = new HashSet(0);

    public Genre() {
    }

    public Genre(String name) {
        this.name = name;
    }

    public Genre(String name, Set books) {
        this.name = name;
        this.books = books;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Set getBooks() {
        return this.books;
    }

    public void setBooks(Set books) {
        this.books = books;
    }
}

src/main/java/ru/javabegin/training/web/controllers/BookListController.java
package ru.javabegin.training.web.controllers;

import java.io.Serializable;
import java.util.Map;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.faces.event.ValueChangeEvent;
import org.primefaces.component.datagrid.DataGrid;
import org.primefaces.context.RequestContext;
import org.primefaces.model.LazyDataModel;
import ru.javabegin.training.web.beans.Pager;
import ru.javabegin.training.web.db.DataHelper;
import ru.javabegin.training.web.entity.ext.BookExt;
import ru.javabegin.training.web.enums.SearchType;
import ru.javabegin.training.web.models.BookListDataModel;

@ManagedBean(eager = true)
@SessionScoped
public class BookListController implements Serializable {

    private SessionUtils sessionUtils = SessionUtils.getInstance();
    
    private DataGrid dataTable;
    private BookExt selectedBook;
    private BookExt newBook;
    private transient DataHelper dataHelper;
    private LazyDataModel<BookExt> bookListModel;
    private Long selectedAuthorId;// текущий автор книги из списка при редактировании книги
    // критерии поиска
    private char selectedLetter; // выбранная буква алфавита, по умолчанию не выбрана ни одна буква
    private SearchType selectedSearchType = SearchType.TITLE;// хранит выбранный тип поиска, по-умолчанию - по названию
    private long selectedGenreId; // выбранный жанр
    private String currentSearchString; // хранит поисковую строку
    private Pager pager;
    //-------
    private boolean editMode;// отображение режима редактирования
    private boolean addMode;// отображение режима добавление

    public BookListController() {
        pager = new Pager();
        dataHelper = new DataHelper(pager);
        bookListModel = new BookListDataModel(dataHelper, pager);
    }

    public DataHelper getDataHelper() {
        return dataHelper;
    }

    public Pager getPager() {
        return pager;
    }

    private void submitValues(Character selectedLetter, long selectedGenreId) {
        this.selectedLetter = selectedLetter;
        this.selectedGenreId = selectedGenreId;
        dataTable.setFirst(0);
    }

    //<editor-fold defaultstate="collapsed" desc="запросы в базу">
    private void fillBooksAll() {
        dataHelper.getAllBooks();
    }

    public void fillBooksByGenre() {

        imitateLoading();

        Map<String, String> params = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap();
        selectedGenreId = Long.valueOf(params.get("genre_id"));
        submitValues(' ', selectedGenreId);
        dataHelper.getBooksByGenre(selectedGenreId);

    }

    public void fillBooksByRate() {

        imitateLoading();
        dataHelper.getBooksByRate();

    }

    public void fillBooksByLetter() {

        imitateLoading();

        Map<String, String> params = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap();
        selectedLetter = params.get("letter").charAt(0);
        submitValues(selectedLetter, -1);
        dataHelper.getBooksByLetter(selectedLetter);

    }

    public void fillBooksBySearch() {

        imitateLoading();

        submitValues(' ', -1);

        if (currentSearchString.trim().length() == 0) {
            fillBooksAll();

        }

        if (selectedSearchType == SearchType.AUTHOR) {
            dataHelper.getBooksByAuthor(currentSearchString);
        } else if (selectedSearchType == SearchType.TITLE) {
            dataHelper.getBooksByName(currentSearchString);
        }

    }

    public void deleteBook() {
        dataHelper.deleteBook(selectedBook);
        dataHelper.populateList();

//        RequestContext.getCurrentInstance().execute("dlgDeleteBook.hide()");
        
        sessionUtils.showMessage("deleted");
        
        dataTable.setFirst(calcSelectedPage());

    }

    public void rate() {
        Map<String, String> params = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap();
        int bookIndex = Integer.parseInt(params.get("bookIndex"));

        BookExt book = pager.getList().get(bookIndex);

        dataHelper.rateBook(book, sessionUtils.getUserName());

    }

    public void saveBook() {

        if (!validateFields()) {
            return;
        }

        if (editMode) {
            dataHelper.updateBook(selectedBook);
        } else if (addMode) {
            dataHelper.addBook(selectedBook.getBook());
        }

        cancelModes();
        dataHelper.populateList();
        
        sessionUtils.showMessage("updated");

        dataTable.setFirst(calcSelectedPage());
    }

    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="режим редактирования">
    public void switchEditMode() {
        editMode = true;
        RequestContext.getCurrentInstance().execute("dlgEditBook.show()");

    }

    public void switchAddMode() {
        addMode = true;
        selectedBook = new BookExt();
        selectedBook.setGenre(dataHelper.getGenre(selectedGenreId));
        RequestContext.getCurrentInstance().execute("dlgEditBook.show()");

    }
    
  

    public void cancelModes() {
        if (addMode) {
            addMode = false;
        }

        if (editMode) {
            editMode = false;
        }

        if (selectedBook != null) {
            selectedBook.setUploadedContent(null);
            selectedBook.setUploadedImage(null);
        }

        RequestContext.getCurrentInstance().execute("dlgEditBook.hide()");
    }

    //</editor-fold>
    public Character[] getRussianLetters() {
        Character[] letters = new Character[]{'А', 'Б', 'В', 'Г', 'Д', 'Е', 'Ё', 'Ж', 'З', 'И', 'Й', 'К', 'Л', 'М', 'Н', 'О', 'П', 'Р', 'С', 'Т', 'У', 'Ф', 'Х', 'Ц', 'Ч', 'Ш', 'Щ', 'Ъ', 'Ы', 'Ь', 'Э', 'Ю', 'Я',};
        return letters;
    }

    public void searchStringChanged(ValueChangeEvent e) {
        currentSearchString = e.getNewValue().toString();
    }

    public void searchTypeChanged(ValueChangeEvent e) {
        selectedSearchType = (SearchType) e.getNewValue();
    }

    private int calcSelectedPage() {
        int page = dataTable.getPage();// текущий номер страницы (индексация с нуля)

        int leftBound = pager.getTo() * (page - 1);
        int rightBound = pager.getTo() * page;

        boolean goPrevPage = pager.getTotalBooksCount() > leftBound & pager.getTotalBooksCount() <= rightBound;


        if (goPrevPage) {
            page--;
        }

        return (page > 0) ? page * pager.getTo() : 0;
    }

    //<editor-fold defaultstate="collapsed" desc="гетеры сетеры">
    public boolean isEditMode() {
        return editMode;
    }

    public boolean isAddMode() {
        return addMode;
    }

    public String getSearchString() {
        return currentSearchString;
    }

    public void setSearchString(String searchString) {
        this.currentSearchString = searchString;
    }

    public SearchType getSearchType() {
        return selectedSearchType;
    }

    public void setSearchType(SearchType searchType) {
        this.selectedSearchType = searchType;
    }

    public long getSelectedGenreId() {
        return selectedGenreId;
    }

    public void setSelectedGenreId(int selectedGenreId) {
        this.selectedGenreId = selectedGenreId;
    }

    public char getSelectedLetter() {
        return selectedLetter;
    }

    public void setSelectedLetter(char selectedLetter) {
        this.selectedLetter = selectedLetter;
    }

    public Long getSelectedAuthorId() {
        return selectedAuthorId;
    }

    public void setSelectedAuthorId(Long selectedAuthorId) {
        this.selectedAuthorId = selectedAuthorId;
    }

    public LazyDataModel<BookExt> getBookListModel() {
        return bookListModel;
    }

    public void setSelectedBook(BookExt selectedBook) {
        this.selectedBook = selectedBook;
    }

    public BookExt getSelectedBook() {
        return selectedBook;
    }

    public DataGrid getDataGrid() {
        return dataTable;
    }

    public void setDataGrid(DataGrid dataTable) {
        this.dataTable = dataTable;
    }

    public BookExt getNewBook() {
        if (newBook == null) {
            newBook = new BookExt();
        }
        return newBook;
    }

    public void setNewBook(BookExt newBook) {
        this.newBook = newBook;
    }

    //</editor-fold>
    private void imitateLoading() {
//        try {
//            Thread.sleep(1000);// имитация загрузки процесса
//        } catch (InterruptedException ex) {
//            Logger.getLogger(BookListController.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }

    private boolean validateFields() {

        if (sessionUtils.isNullOrEmpty(selectedBook.getAuthor())
                || sessionUtils.isNullOrEmpty(selectedBook.getDescr())
                || sessionUtils.isNullOrEmpty(selectedBook.getGenre())
                || sessionUtils.isNullOrEmpty(selectedBook.getIsbn())
                || sessionUtils.isNullOrEmpty(selectedBook.getName())
                || sessionUtils.isNullOrEmpty(selectedBook.getPageCount())
                || sessionUtils.isNullOrEmpty(selectedBook.getPublishYear())
                || sessionUtils.isNullOrEmpty(selectedBook.getPublisher())) {
            sessionUtils.failValidation("error_fill_all_fields");
            return false;

        }
        
        
        if (dataHelper.isIsbnExist(selectedBook.getIsbn(), selectedBook.getId())){
            sessionUtils.failValidation("error_isbn_exist");
            return false;            
        }

        if (addMode) {

            if (selectedBook.getUploadedContent() == null) {
                sessionUtils.failValidation("error_load_pdf");
                return false;
            }

            if (selectedBook.getUploadedImage() == null) {
                sessionUtils.failValidation("error_load_image");
                return false;
            }

        }


        return true;


    }

   

   
}

src/main/java/ru/javabegin/training/web/controllers/GenreController.java
package ru.javabegin.training.web.controllers;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.model.SelectItem;
import ru.javabegin.training.web.beans.Pager;
import ru.javabegin.training.web.comparators.ListComparator;
import ru.javabegin.training.web.db.DataHelper;
import ru.javabegin.training.web.entity.ext.GenreExt;

@ManagedBean
@SessionScoped
public class GenreController implements Serializable, Converter {

    private List<SelectItem> selectItems = new ArrayList<SelectItem>();
    private Map<Long, GenreExt> map;
    private List<GenreExt> list;
    private Pager pager;
    private DataHelper dataHelper;
    @ManagedProperty(value = "#{bookListController}")
    private BookListController bookListController;

    @PostConstruct
    public void init() {
        pager = bookListController.getPager();
        dataHelper = bookListController.getDataHelper();

        map = new HashMap<Long, GenreExt>();
        list = dataHelper.getAllGenres();
        Collections.sort(list, ListComparator.getInstance());
        
        list.add(0, createEmptyGenre());

        for (GenreExt genre : list) {
            map.put(genre.getId(), genre);
            selectItems.add(new SelectItem(genre, genre.getName()));
        }

    }

    public List<SelectItem> getSelectItems() {
        return selectItems;
    }

    public List<GenreExt> getGenreList() {
        return list;
    }

    @Override
    public Object getAsObject(FacesContext context, UIComponent component, String value) {
        return map.get(Long.valueOf(value));
    }

    @Override
    public String getAsString(FacesContext context, UIComponent component, Object value) {
        return ((GenreExt) value).getId().toString();
    }

    public BookListController getBookListController() {
        return bookListController;
    }

    public void setBookListController(BookListController bookListController) {
        this.bookListController = bookListController;
    }

    private GenreExt createEmptyGenre() {
        GenreExt genre = new GenreExt();
        genre.setId(-1L);
        genre.setName("");
        return genre;
    }
}

src/main/webapp/templates/footer.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <ui:composition>


            <div id="footer">
                <div class="footer-wrap">
                    <p>© 2013 "#{msg.online_library}"</p>
                </div>
            </div>


        </ui:composition>
    </h:body>
</html>

src/main/webapp/templates/genres.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Facelet Title</title>
    </h:head>

    <h:body>
        <ui:composition>

            <div class="left-menu">
                <h:form styleClass="genres" id="genresForm">
                    <ul>


                        <ui:repeat value="#{genreController.genreList}" var="g">
                            <li>
                                <p:commandLink update=":booksForm:booksList @form :lettersForm :booksCount" value="#{g.name}" styleClass="#{g.id == bookListController.selectedGenreId ? 'selected_link':''}" actionListener="#{bookListController.fillBooksByGenre()}">
                                    <f:param name="genre_id" value="#{g.id}" />
                                </p:commandLink>

                            </li>
                        </ui:repeat>


                    </ul>
                </h:form>
            </div>

        </ui:composition>
    </h:body>
</html>

src/main/webapp/templates/header.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"

      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>Facelet Title</title>

    </h:head>
    <h:body>
        <ui:composition>

            <div class="header-wrap">


                <div class="language">
                    <ui:include src="/templates/locales.xhtml"/>
                </div>

                <div class="social">
                    <a href="http://vk.com/javabegin" target="_blank"> <h:graphicImage library="images" name="vk.jpg" width="16" height="16"/></a>
                    <a href="#"> <h:graphicImage library="images" name="facebook.jpg" width="16" height="16"/></a>
                </div>

                <div class="aut">
                    <p>#{user.username}</p>
                    <h:form>
                        <h:commandLink action="#{user.logout()}" value="#{msg.exit}"/>
                    </h:form>
                </div>

            </div>

        </ui:composition>
    </h:body>
</html>

src/main/webapp/templates/letters.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <ui:composition>


            <div class="nav">

                <h:form id="lettersForm">
                    <ul>
                        <ui:repeat value="#{bookListController.russianLetters}" var="letter">
                            <li>
                                <p:commandLink value="#{letter}" styleClass="#{letter == bookListController.selectedLetter ? 'selected':''}" actionListener="#{bookListController.fillBooksByLetter()}" update=":genresForm  :booksForm:booksList @form :lettersForm   :booksCount">
                                    <f:param name="letter" value="#{letter}" />
                                </p:commandLink>                            </li>
                        </ui:repeat>
                    </ul>
                </h:form>




            </div>


        </ui:composition>
    </h:body>
</html>

src/main/webapp/templates/library.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <f:view locale="#{localeChanger.currentLocale}">  
        <h:head>
            <title><ui:insert name="title"/></title>  

        </h:head>
        <h:body>


            <f:facet name="last">
                <h:outputScript library="js" name="library.js" target="head"/>
                <h:outputStylesheet library="css" name="main.css" />
                <h:outputStylesheet library="css" name="dialog.css" />
            </f:facet>


            <p:ajaxStatus id="ajaxStatusPanel">  
                <f:facet name="start">      
                    <div id="loading_wrapper">
                        <p>#{msg.loading}...</p>
                    </div>
                </f:facet>  

                <f:facet name="complete">  
                    <h:outputText value="" />  
                </f:facet>  
            </p:ajaxStatus>  


            <div class="header">

                <ui:include src="/templates/header.xhtml"/>
            </div>


            <div id="wrap">

                <ui:include src="/templates/logo.xhtml"/>
                <ui:include src="/templates/search.xhtml"/>
                <ui:include src="/templates/letters.xhtml"/>



                <div class="content">

                    

                    <ui:include src="/templates/genres.xhtml"/>


                    <div class="right-content">

                        <ui:insert name="books_count"/>

                        <ui:insert name="content"/>



                        <div class="clear"></div>





                    </div>
                </div>

                <div class="footer_blank"></div>

            </div>

            <ui:include src="/templates/footer.xhtml"/>



        </h:body>
    </f:view>
</html>

src/main/webapp/templates/locales.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <ui:composition>


            <div class="lang">


                <h:form style="display: inline;">

                    <h:commandLink  actionListener="#{localeChanger.changeLocale('ru')}">
                        <h:graphicImage styleClass="#{localeChanger.currentLocale == 'ru' ? 'active':''}" library="images" name="rus.png" title="#{msg.russian}" width="16" height="13"/>                        
                    </h:commandLink>


                    <h:commandLink actionListener="#{localeChanger.changeLocale('en')}">
                        <h:graphicImage styleClass="#{localeChanger.currentLocale == 'en' ? 'active':''}"  library="images" name="usa.png" title="#{msg.english}" width="16" height="13"/>                        
                    </h:commandLink>
                    
                    

                </h:form>


            </div>




        </ui:composition>
    </h:body>
</html>

src/main/webapp/templates/logo.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <ui:composition>
            <div id="wrap">

                <div class="logo">
                    <a href="#">
                        <h:graphicImage library="images/#{localeChanger.currentLocale}" name="logo.png"/>
                    </a>
                </div>

                <div class="menu">

                    <h:form>
                        <ul>
                            <li><a href="#">#{msg.new}</a></li>

                            <li><p:commandLink update=":booksForm:booksList :lettersForm :booksCount" value="#{msg.popular}" actionListener="#{bookListController.fillBooksByRate()}"/>

                            </li>
                            <li><p:commandLink type="button" onclick="dlgAbout.show()" value="#{msg.about}" global="false"/>    </li>    
                            <li><a href="#">#{msg.contacts}</a></li>
                            <li><a href="#">#{msg.team}</a></li>
                        </ul>
                    </h:form>


                </div>

                <h:form>
                    <p:commandLink value="#{msg.feedback}" action="#{mailController.showMailForm()}" styleClass="feedback" update=":formSendMail"/>
                </h:form>
                <div class="clear"></div>

            </div>
        </ui:composition>
    </h:body>
</html>

src/main/webapp/templates/search.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>

        <ui:composition>
            <div class="search">


                <h:form styleClass="search_form" id="search_form">


                    <input type="submit" class="button-text"></input>


                    <h:inputText  id="search_string" styleClass="search-text" value="#{bookListController.searchString}"/>

                    <p:commandButton id="btnSearch" value="#{msg.search}" styleClass="button" actionListener="#{bookListController.fillBooksBySearch}" update=":booksForm:booksList @form :lettersForm :genresForm :booksCount"/>


                    <div class="dropdown">
                        <h:selectOneMenu id="search_select" styleClass="select_search" value="#{bookListController.searchType}">
                            <f:selectItems value="${searchTypeController.searchList}" />
                        </h:selectOneMenu>
                    </div>

                    <script language="javascript">
                          document.getElementById("search_form:search_string").setAttribute("placeholder","#{msg.search_book}");
                    </script>

                    <p:defaultCommand target="btnSearch" />

                </h:form>







                <div class="clear"></div>



            </div>





        </ui:composition>

    </h:body>
</html>